<a href="https://colab.research.google.com/github/Abelbimaw/Programming-Python/blob/main/Simple_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


In [5]:
training_input = np.array([[0,0,1],
                           [1,1,1],
                           [1,0,1],
                           [0,1,1]])
print(training_input)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]


In [6]:
training_output = np.array([[0,1,1,0]]).T
print(training_output)

[[0]
 [1]
 [1]
 [0]]


In [7]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [20]:
def sigmoid_derivate(x):
  return x*(1-x)

In [18]:
np.random.seed(1)
synaptic_weight = 2 * np.random.random((3,1)) - 1
synaptic_weight

array([[-0.39533485],
       [-0.70648822],
       [-0.81532281]])

In [23]:
for interaction in range(20000):
  #forward propagation
  input_layer = training_input
  output = sigmoid(np.dot(input_layer, synaptic_weight))

  #backward propagation
  error = training_output - output
  adjust = error * sigmoid_derivate(output)
  synaptic_weight += np.dot(input_layer.T, adjust)

print("Weight after training")
print(synaptic_weight) 

print("Output of Training: ")
print(output)


Weight after training
[[10.47727286]
 [-0.20657399]
 [-5.03289254]]
Output of Training: 
[[0.00647784]
 [0.99471605]
 [0.99569797]
 [0.00527523]]


In [24]:
for j in output:
  print(np.around(j))

[0.]
[1.]
[1.]
[0.]
